### ISSUE TITLE
Move on click listeners to their own .java files

### ISSUE THREAD

**Issue by apmcleod** [jimmyfnugent/tic-tac-go#17]
Do we want to do this? It would create lots of very small java files, but it would also clean up TicTacGo.java substantially. I would vote for doing this, probably within a listeners directory or something like that.

**Comment by jimmyfnugent** [comment]
We don't need to move them to their own files, but the game should be in its own activity (not the same one as the menu). The listeners can be their own internal classes if they're getting a bit large to be anonymous.

**Comment by jimmyfnugent** [comment]
Marking as fixed -- feel free to reopen if anyone disagrees.
