### ISSUE TITLE
Allow multi-piece spaces to contribute to winning

### ISSUE THREAD

**Issue by jimmyfnugent** [jimmyfnugent/tic-tac-go#2]
We allow a single space to have up to two pieces in it, so we need to decide if such a space should be counted in a winning combination. apmcleod suggests that it should, and I agree.

**Comment by apmcleod** [comment]
See also #6

**Comment by apmcleod** [comment]
After playing some more games, I'm convinced that allowing spaces with 2 different pieces to contribute to a win is necessary. It would be essentially impossible to have a 3-in-a-row with only your own pieces in each space.

I allow multi-piece winning spaces in #19
