### ISSUE TITLE
Direction chooser popup misalligned

### ISSUE THREAD

**Issue by apmcleod** [jimmyfnugent/tic-tac-go#21]
Every direction chooser popup seems to be too high up on the screen (by about the height of the status bar on my phone...). This results in the top three choices being invisible on the top row, and a gap below the popup on the bottom row.

**Comment by apmcleod** [comment]
Interesting note, when I made the changes to the layout xml file in #23, the status bar disappeared and this issue was fixed. I don't think the game is complex enough to warrant removing the status bar, so I'm going to leave this open. (Also, future changes in the direction-picker branch will mess with this).

**Comment by jimmyfnugent** [comment]
Probably has to do with the theme. We can figure it out once we've made our other changes.

**Comment by apmcleod** [comment]
This should become permanently fixed after #27. The status bar issue I think will be grouped together with #22
