### ISSUE TITLE
Add piece animations

### ISSUE THREAD

**Issue by jimmyfnugent** [jimmyfnugent/tic-tac-go#30]
Tracking bug for adding animations so pieces actually move between turns.

As a side note, this should make it way clearer what actually happened each turn :-)

**Comment by apmcleod** [comment]
Hopefully the animations will help with that. Maybe we can add a replay animation button or something as well.

**Comment by apmcleod** [comment]
We now have 2 attempts at animations. I switched the code over to using coordinates to lay out (top,left margins), and essentially took Jimmy's animation code and reworked it with that in mind.

Animations and collisions (even halfway ones) are animating properly now, though there is a slight pause halfway while it figures out what to do. We could possibly try to pre-compute this if it bothers anyone.

**Comment by apmcleod** [comment]
One thing we need to figure out still is wraparounds (presumably by creating some dummy pieces somewhere). The board will not show Pieces outside of its bounds, so we could just create a bunch of dummy Pieces in the case that a Piece will cross an edge.

After animation is completed, we call TTGGameActivity.updateBoard() which removes all ImageViews from the board and repopulates it, which would clear the dummy Pieces.
