### ISSUE TITLE
Make multi-piece spaces look good

### ISSUE THREAD

**Issue by jimmyfnugent** [jimmyfnugent/tic-tac-go#7]
It's hard to tell if there are multiple pieces from the same player in a single space.

**Comment by apmcleod** [comment]
Are the two directions showing up at all? What I seem to remember is that the ordering of what you draw is important, since a piece will cover the direction of the identical piece below it. We had to take care to first draw a piece with one direction, and then make the top layer the direction only.

**Comment by jimmyfnugent** [comment]
Yeah, that's exactly it. It's possible to tell if you look closely -- it's just hard.
